### ISSUE TITLE
Lead maintainer wanted

### ISSUE THREAD

**Issue by mcollina** [mcollina/coap-cli#10]
As you probably have seen, I have been neglecting this module for the last few months. I think it will be better if someone else does the releases, and ensures general quality of the received contributions.

cc @nqd @dmoranj @neich @boneskull @neophob

**Comment by gerdemann** [comment]
Hey @mcollina,
if you like, we can try to maintain the project further.
Best regards,
Michael

**Comment by mcollina** [comment]
Also http://npm.im/coap?

**Comment by gerdemann** [comment]
Yes, we can try to do that.

**Comment by mcollina** [comment]
What's your npm handle? I'll add you there as well.

**Comment by gerdemann** [comment]
my npm handle is "gerdemann"

**Comment by mcollina** [comment]
Done! Good luck!

**Comment by gerdemann** [comment]
Thanks!
Is it possible that you're transferring the repo to our org ("avency")?
Then we can adjust the Github Settings etc. as well.

What about http://npm.im/coap? Shall we take over that as well?

**Comment by mcollina** [comment]
You need to add me to that org and remove your fork:

> avency/coap-cli already exists and You don’t have the permission to create repositories on avency

^ that's the error I'm getting.

**Comment by gerdemann** [comment]
done

**Comment by mcollina** [comment]
You'll need to remove your fork unfortunately

> avency already has a repository in the mcollina/coap-cli network

**Comment by gerdemann** [comment]
It's deleted now, I'm sorry.
