### ISSUE TITLE
Add option -H <headers>  (for e.g. auth headers)

### ISSUE THREAD

**Issue by fambon** [mcollina/coap-cli#14]
some coap brokers e.g. Meshblu require authentication on most requests, and they use "headers" (aka "options" in coap) to pass credentials.

providing option `-H <headers>` would help talk to these servers.

https://www.npmjs.com/package/coap#registerOption
https://www.npmjs.com/package/coap#setOption

**Comment by mcollina** [comment]
Send a PR :). I'm not really implementing new features here.

**Comment by fambon** [comment]
the octoblu guys did it in their fork - back in Aug 2014 - but no PR.
https://github.com/octoblu/coap-cli

**Comment by fambon** [comment]
Looks as if they do a very specific use of options 98 and 99 ; their "basic auth" mechanism using options might be in effect Meshblu-coap only.  I used their forked client.

This does not seem to be a very generic nor widely used means of performing auth. I will just close this issue.

**Comment by gerdemann** [comment]
The feature is now available (#24)
